// <auto-generated />
using System;
using Lot.Shared.Infraestructure.Persistence.EFC.Configuration.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lot.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email_Unique");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Lot.Inventaries.Domain.Model.Aggregates.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(6)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StockTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Lot.Inventaries.Domain.Model.Aggregates.InventoryByBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("Cantidad");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("FechaEntrada");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Proveedor");

                    b.Property<int>("UnidadId")
                        .HasColumnType("integer")
                        .HasColumnName("UnidadId");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("IX_InventoryByBatch_ProductoId");

                    b.HasIndex("UnidadId")
                        .HasDatabaseName("IX_InventoryByBatch_UnidadId");

                    b.ToTable("inventory_by_batch", (string)null);
                });

            modelBuilder.Entity("Lot.Inventaries.Domain.Model.Aggregates.InventoryByProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("Cantidad");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp(6)")
                        .HasColumnName("FechaEntrada");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductoId");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("StockMinimo");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("IX_InventoryByProduct_ProductoId");

                    b.ToTable("inventory_by_product", (string)null);
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("combos", (string)null);
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.ComboItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComboId")
                        .HasColumnType("integer")
                        .HasColumnName("ComboId");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("ProductId");

                    b.ToTable("combo_items", (string)null);
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("UnitId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("ProductId");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("ProductId", "TagId")
                        .IsUnique();

                    b.ToTable("product_tags", (string)null);
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("units_of_measure", (string)null);
                });

            modelBuilder.Entity("Lot.Reports.Domain.Model.Aggregates.CategoryReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductosBajoStock")
                        .HasColumnType("integer");

                    b.Property<int>("StockTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TotalProductos")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotalInventario")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("category_reports", (string)null);
                });

            modelBuilder.Entity("Lot.Reports.Domain.Model.Aggregates.StockAverageReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PorcentajeBajoStock")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProductosBajoStock")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimoPromedio")
                        .HasColumnType("integer");

                    b.Property<decimal>("StockPromedioReal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TotalProductos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("stock_average_reports", (string)null);
                });

            modelBuilder.Entity("Lot.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ComboId")
                        .HasColumnType("integer");

                    b.Property<string>("ComboName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComboId")
                        .HasDatabaseName("IX_Sales_ComboId");

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("IX_Sales_CustomerName");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Sales_ProductId");

                    b.HasIndex("SaleDate")
                        .HasDatabaseName("IX_Sales_SaleDate");

                    b.ToTable("sales", (string)null);
                });

            modelBuilder.Entity("Lot.Inventaries.Domain.Model.Aggregates.InventoryByBatch", b =>
                {
                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Lot.Inventaries.Domain.Model.Aggregates.InventoryByProduct", b =>
                {
                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.ComboItem", b =>
                {
                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Combo", "Combo")
                        .WithMany("ComboItems")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Product", b =>
                {
                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Unit", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.ProductTag", b =>
                {
                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lot.ProductManagement.Domain.Model.Aggregates.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Lot.Sales.Domain.Model.Aggregates.Sale", b =>
                {
                    b.OwnsOne("Lot.Sales.Domain.Model.ValueObjects.SalePrice", "UnitPrice", b1 =>
                        {
                            b1.Property<int>("SaleId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("SaleId");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("Lot.Sales.Domain.Model.ValueObjects.SaleQuantity", "Quantity", b1 =>
                        {
                            b1.Property<int>("SaleId")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Quantity");

                            b1.HasKey("SaleId");

                            b1.ToTable("sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Combo", b =>
                {
                    b.Navigation("ComboItems");
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Product", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("Lot.ProductManagement.Domain.Model.Aggregates.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
